"""Init schema

Revision ID: 1a44a58ebd31
Revises: 
Create Date: 2026-07-15 12:34:07.765507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a44a58ebd31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_placed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first', sa.String(length=255), nullable=False),
    sa.Column('last', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('zipcode', sa.String(length=20), nullable=False),
    sa.Column('order_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_status', sa.Enum('PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'FULFILLED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_placed_email'), 'orders_placed', ['email'], unique=False)
    op.create_index(op.f('ix_orders_placed_first'), 'orders_placed', ['first'], unique=False)
    op.create_index(op.f('ix_orders_placed_last'), 'orders_placed', ['last'], unique=False)
    op.create_index(op.f('ix_orders_placed_order_status'), 'orders_placed', ['order_status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('TOP', 'BOTTOM', 'OUTERWEAR', 'ACCESSORY', name='productcategory'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('shopping_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_carts_session_id'), 'shopping_carts', ['session_id'], unique=True)
    op.create_table('all_ordered_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders_placed.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_all_ordered_items_order_id'), 'all_ordered_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_all_ordered_items_product_id'), 'all_ordered_items', ['product_id'], unique=False)
    op.create_table('items_in_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['shopping_carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_in_cart_cart_id'), 'items_in_cart', ['cart_id'], unique=False)
    op.create_index(op.f('ix_items_in_cart_product_id'), 'items_in_cart', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_in_cart_product_id'), table_name='items_in_cart')
    op.drop_index(op.f('ix_items_in_cart_cart_id'), table_name='items_in_cart')
    op.drop_table('items_in_cart')
    op.drop_index(op.f('ix_all_ordered_items_product_id'), table_name='all_ordered_items')
    op.drop_index(op.f('ix_all_ordered_items_order_id'), table_name='all_ordered_items')
    op.drop_table('all_ordered_items')
    op.drop_index(op.f('ix_shopping_carts_session_id'), table_name='shopping_carts')
    op.drop_table('shopping_carts')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_placed_order_status'), table_name='orders_placed')
    op.drop_index(op.f('ix_orders_placed_last'), table_name='orders_placed')
    op.drop_index(op.f('ix_orders_placed_first'), table_name='orders_placed')
    op.drop_index(op.f('ix_orders_placed_email'), table_name='orders_placed')
    op.drop_table('orders_placed')
    # ### end Alembic commands ###
