apiVersion: v2
name: kevryx
description: Kubernetes deployment chart for the Kevryx application

type: application

dependencies:
  - name: redis
    version: "27.0.14"
    repository: "https://charts.bitnami.com/bitnami"

version: 0.3.0

appVersion: "1.0.0"