backend:
  image: ghcr.io/user01377/kevryx-backend:prod

frontend:
  image: ghcr.io/user01377/kevryx-frontend:prod

redis:
  enabled: true

  architecture: standalone

  auth:
    enabled: true
    existingSecret: redis-secret
    existingSecretPasswordKey: redis-password

  master:
    persistence:
      enabled: true
      size: 8Gi

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi