backend:
  image: kevryx-backend:dev

frontend:
  image: kevryx-frontend:dev

redis:
  enabled: true

  architecture: standalone

  auth:
    enabled: true
    existingSecret: redis-secret
    existingSecretPasswordKey: redis-password

  master:
    persistence:
      enabled: true
      size: 8Gi

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi