name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend:
    name: Backend Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Backend Test Image
        run: docker build --target test -t kevryx-backend:test backend

      - name: Ruff Testing
        run: docker run --rm kevryx-backend:test ruff check .

      - name: Run Formatting
        run: docker run --rm kevryx-backend:test ruff format --check .

      - name: Run Tests
        run: |
          docker run --rm \
            kevryx-backend:test \
            pytest -q --strict-markers

  frontend:
    name: Frontend Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Frontend Test Image
        run: docker build --target test -t kevryx-frontend:test frontend
      
      - name: Run Linting
        run: docker run --rm kevryx-frontend:test npm run lint
      
      - name: Run Tests
        run: docker run --rm kevryx-frontend:test npm run test

      
  image-build:
    name: Build Docker Images
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Backend Runtime Image
        run: |
          docker build \
            -t ghcr.io/user01377/kevryx-backend:${{ github.sha }} \
            -t ghcr.io/user01377/kevryx-backend:prod \
            backend

      - name: Build Frontend Runtime Image
        run: |
          docker build \
            -t ghcr.io/user01377/kevryx-frontend:${{ github.sha }} \
            -t ghcr.io/user01377/kevryx-frontend:prod \
            frontend

      - name: Push Images To Registry
        run: |
          docker push ghcr.io/user01377/kevryx-backend:${{ github.sha }}
          docker push ghcr.io/user01377/kevryx-backend:prod
          docker push ghcr.io/user01377/kevryx-frontend:${{ github.sha }}
          docker push ghcr.io/user01377/kevryx-frontend:prod